### ISSUE TITLE
Bug: Der Upload von .xml Files um die Zahlungseingänge mit der DB abzugleichen funktioniert nicht

### ISSUE THREAD

**Issue by noahliechti** [hitobito/hitobito_cevi#70]
**Ist**
Testweise wurde ein Rechnungen mit orangem EZ erstellt und bezahlt. Anschliessend wurde versucht einen Export aus dem E-Banking der Region (.xml File der Bank Linth) in die DB zu importieren, um die Zahlungseingänge mit der DB abzugleichen - leider erfolglos.

**Soll**
.xml Files müssen importiert werden können um die Zahlungseingänge mit der DB abzugleichen.

**Hypothese**
Die Daten des .xml Files sehen vermutlich anders aus bei QR-Rechnungen als bei Rechnungen mit orangem EZ. Es ist möglich, dass die Importfunktion bei QR-Zahlungen funktionieren würde. 

### ToDo

- [x] XML-Datei besorgen
- [x] Sicherstellen, dass CAMT.054 verwendet wird
- [x] lokal reproduzieren
- [x] Fehler finden und beheben... :-)

**Comment by nchiapol** [comment]
Bitte im Integrationssystem testen und bestätigen, dass das Problem dort noch auftritt.

**Comment by noahliechti** [comment]
Okay, habe es weitergeleitet.

**Comment by CalvinYMCA** [comment]
Problem scheint laut Seki Region WS weiterhin zu bestehen. Ich versuche noch detailiertere Infos zu erhalten.

**Comment by lechippo** [comment]
Ich habe mithilfe eines CAMT.054 Export von Bank Linth den Fehler reproduziert.
Durch das hinzufügen von `<AcctSvcrRef></AcctSvcrRef>` in den Refs, kann der Import durchgeführt werden.
Meine Hypothese ist, dass dieses Feld zwingend ist. Die Zahlung kann aber trotzdem zugewiesen werden.

**Comment by ThomasEllenberger** [comment]
Um diesen Bug angehen und beheben zu können bräuchten wir unbedingt ein Beispielfile, welches nicht funktioniert hat, um dies entsprechend Testen/Nachverfolgen zu können.
@CalvinYMCA , @lechippo , @nchiapol : Falls möglich bitte wenn das Problem das nächste Mal auftritt uns entsprechend informieren und das dazugehörige File an uns weiterleiten.

**Comment by lechippo** [comment]
Ich habe hier ein Beispielfile
```
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:camt.054.001.04" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <BkToCstmrDbtCdtNtfctn>
    <GrpHdr>
      <MsgId>M/2094650161/CAM</MsgId>
      <CreDtTm>2021-04-29T17:23:53+02:00</CreDtTm>
      <MsgPgntn>
        <PgNb>1</PgNb>
        <LastPgInd>true</LastPgInd>
      </MsgPgntn>
    </GrpHdr>
    <Ntfctn>
      <Id>M/2094650161/CAM</Id>
      <CreDtTm>2021-04-29T17:23:53+02:00</CreDtTm>
      <FrToDt>
        <FrDtTm>2021-04-26T00:00:00+02:00</FrDtTm>
        <ToDtTm>2021-04-28T00:00:00+02:00</ToDtTm>
      </FrToDt>
      <Acct>
        <Id>
          <IBAN>CH2008731549539472001</IBAN>
        </Id>
        <Ccy>CHF</Ccy>
        <Ownr>
          <Nm>Cevi Region Winterthur-Schaffhausen</Nm>
        </Ownr>
        <Svcr>
          <FinInstnId>
            <BICFI>LINSCH23XXX</BICFI>
          </FinInstnId>
        </Svcr>
      </Acct>
      <Ntry>
        <NtryRef>010005915</NtryRef>
        <Amt Ccy="CHF">30</Amt>
        <CdtDbtInd>CRDT</CdtDbtInd>
        <Sts>BOOK</Sts>
        <BookgDt>
          <Dt>2021-04-26</Dt>
        </BookgDt>
        <ValDt>
          <Dt>2021-04-26</Dt>
        </ValDt>
        <AcctSvcrRef>O/460872248</AcctSvcrRef>
        <BkTxCd>
          <Domn>
            <Cd>PMNT</Cd>
            <Fmly>
              <Cd>RCDT</Cd>
              <SubFmlyCd>VCOM</SubFmlyCd>
            </Fmly>
          </Domn>
        </BkTxCd>
        <NtryDtls>
          <Btch>
            <NbOfTxs>1</NbOfTxs>
            <TtlAmt Ccy="CHF">30</TtlAmt>
            <CdtDbtInd>CRDT</CdtDbtInd>
          </Btch>
          <TxDtls>
            <Refs>
              <MsgId>812726000000300000000000393</MsgId>
              <InstrId>15694523908/6XXX</InstrId>
              <EndToEndId>NOTPROVIDED</EndToEndId>
            </Refs>
            <Amt Ccy="CHF">30</Amt>
            <CdtDbtInd>CRDT</CdtDbtInd>
            <BkTxCd>
              <Domn>
                <Cd>PMNT</Cd>
                <Fmly>
                  <Cd>RCDT</Cd>
                  <SubFmlyCd>VCOM</SubFmlyCd>
                </Fmly>
              </Domn>
            </BkTxCd>
            <RltdPties>
              <Dbtr>
                <Nm>Hans Muster
Musterstrasse 39
8400 Winterthur
Schweiz</Nm>
                <PstlAdr>
                  <AdrLine>Hans Muster
Musterstrasse 39
8400 Winterthur
Schweiz</AdrLine>
                </PstlAdr>
              </Dbtr>
              <DbtrAcct>
                <Id>
                  <IBAN>CH9480808007130661439</IBAN>
                </Id>
              </DbtrAcct>
            </RltdPties>
            <RmtInf>
              <Strd>
                <CdtrRefInf>
                  <Tp>
                    <CdOrPrtry>
                      <Prtry>ISR Reference</Prtry>
                    </CdOrPrtry>
                  </Tp>
                  <Ref>812726000000300000000000393</Ref>
                </CdtrRefInf>
              </Strd>
            </RmtInf>
          </TxDtls>
        </NtryDtls>
      </Ntry>
    </Ntfctn>
  </BkToCstmrDbtCdtNtfctn>
</Document>
```
