### ISSUE TITLE
EVENTS: Konfiguration pro Kurs, ob direkt angemeldet, oder manuell zugewiesen (Warteliste)

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_cevi#79]
Kurs-Marktplatz: hier sehen wir keinen Bedarf. Das bestehende Tab "Anmeldungen" bzw. die damit verknüpfte Warteliste möchten wir aber nutzen. 

### Tech spec
- Umsetzung von `supports_applications` pro Kurs im Core, Umsetzung von ausgeblendeter `priorization` im Cevi Wagon.
- In Abklärung: Möglicherweise muss `supports_applications` bei der PBS bei Kursen immer auf `true` forciert werden.
- Unten wird von Ablauf a. und Ablauf b. gesprochen. Erklärung siehe erster Kommentar vom Cevi auf diesem Ticket.
- Der Ablauf a. ist aktuell bei Anlässen der Fall (weil Event.supports_applications == false)
- Der Ablauf b. ist aktuell bei Kursen der Fall, wenn das Flag priorization auf false gesetzt ist (weil Event::Course.supports_applications == true)
- Neu soll es auf Kursen möglich sein, zwischen Ablauf a. und Ablauf b. zu wählen.
  - `Event.supports_applications` ist bisher ein class_attribute: https://github.com/hitobito/hitobito/blob/master/app/models/event.rb#L77. Bei Kursen ist das im Core bisher pauschal auf `true` gesetzt. Neu soll das via ein Datenbankfeld steuerbar werden.
- Caveat: Wenn ein Kurs bereits Anmeldungen auf der Warteliste hat, und dann von Ablauf b. zu Ablauf a. geswitcht wird, dann verschwindet das Anmeldungen-Tab, und die Einträge auf der Warteliste sind nicht mehr sichtbar. Abklären mit Cevi ob das okay ist.

### TODO
- [x] Neues boolean Datenbankfeld `supports_applications` auf `Event::Course`, default true, not nullable
- [x] Neues Feld im Formular anzeigen (in der Nähe des render_extensions Hooks `application_middle_fields`) und in den permitted attrs eintragen
- [x] Aus den used_attributes von `Event::Course` das Attribut `priorization` herausnehmen
- [x] Kosmetik: Auf dem Tab Anmeldungen (nur sichtbar bei Kursen die `supports_applications == true` haben) muss noch jegliche Referenz zu Prio und (nationaler) Warteliste entfernt werden. Das meiste müsste schon automatisch geschehen sein, aber der Link um eine Anmeldung auf die (nationale) Warteliste zu setzen wird dort fälschlicherweise noch stehen. Daher **im Core** im entsprechenden [Partial](https://github.com/hitobito/hitobito/blob/master/app/views/event/application_market/_waiting_list_link.html.haml#L1) noch ein Check nach `p.event.attr_used?(:priorization)` einfügen. Nur wenn `:priorization` auf einem Event aktivierbar ist, macht es Sinn diesen Link anzuzeigen.
- [ ] In Abklärung: Möglicherweise muss `supports_applications` bei der PBS bei Kursen immer auf `true` forciert werden.
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
Bei uns gibt es grundsätzlich zwei Typen von Anmelde-Abläufen:
  a. Eine Person meldet sich an und ist (sofern Platz verfügbar) sofort angemeldet.
  b. Eine Person meldet sich an, die Anmeldung erscheint dann auf dem Tab "Anmeldungen". Sie wird anschliessend noch manuell geprüft und falls alles OK ist dem vorgesehenen Kurs zugewiesen.

Die Kurs-Marktplatz funktion bei der die Person mehrere mögliche Angebote auswählen kann und dann einem davon zugwiesen wird verwenden wir nicht.

Wir möchten, dass pro Kurs konfiguriert werden kann ob Ablauf (a) oder (b) gilt.

**Comment by nchiapol** [comment]
Vielen dank für die Arbeit, ich habe eben damit herumgespielt. Folgende Dinge sind mir aufgefallen:
  * Sollte die neue Checkbox in Anbetracht des Naming in #80 nicht "Verwendet Voranmeldung" heissen. (Vorschlag für Beschrieb: "Teilnehmende können sich selbst nur voranmelden und müssen dann manuell zugewiesen werden")
  * Die Verwaltungsknöpfe zwischen Anlässen und Kursen sind sehr unterschiedlich (Bei Anlässen fehlen die Buttons "Anmeldung löschen", "Abmelden" und "Nicht erschienen"). Dessen war ich mir nicht bewusst. Damit können wir leben, ist aber IMO ein unnötiger und verwirrender Unterschied.
  * Möglicherweise als Folge dieser Unterschiede gibt es noch verschiedene Probleme mit der neuen Einstellung:
    * Wenn ich bei einem Kurs "Verwendet Warteliste" ausgeschaltet habe und sich jemand anmeldet, kann ich die Person nicht Anmeldung nicht löschen (workaround: Rolle im Kursteam hinzufägen und TN rolle löschenlassen, dann Team Rolle manuell löschen)
![image](https://user-images.githubusercontent.com/1123483/201206487-32b0d590-159a-4262-b661-6db93661b907.png)
    * Wenn ich nach dieser Anmeldung die Einstellung "Verwendet Warteliste" einschalte, erscheint das "Anmeldungen" Tab. Wenn ich dort auf den "nach rechts"-Pfeil klicke bekomme ich
![image](https://user-images.githubusercontent.com/1123483/201206928-0b68864c-8a97-423d-8f8f-3c52c7d1c6a2.png)
    * Das Caveat oben (Voranmeldungen auf dem "Anmeldungen"-Tab verschwinden) ist unschön aber ich denke damit können wir leben. Falls mit wenig Aufwand machbar, wäre es natürlich schöner wenn dann das Umstellen mit einer Warnung verweigert würde.

**Comment by ThomasEllenberger** [comment]
Finde den Vorschlag von @nchiapol gut, das neue Tag "Verwendet Voranmeldung" zu nennen, damit es nicht zur Verwechslung mit der Warteliste kommt.

Habe das Issue kurz getestet, dabei ist mir noch folgendes aufgefallen:
Hat man bei einem Kurs sowohl "Verwendet Warteliste" wie auch "Warteliste" aktiv, so landen Personen welche sich anmelden bei den Anmeldungen direkt links, bei den Zugeteilten Teilnehmenden, anstatt bei den Anmeldungen. 
Hat man nur "Verwendet Warteliste" aktiviert, landen sie erst rechts bei Anmeldungen und müssen dann manuell rübergeschoben werden. Dies müsste meines Erachtens auch so funktionieren wenn beide Angewählt sind. Oder kommt dies nie vor? Müssten die jeweiligen Funktionen dann exklusiv sein, so dass man nur eine der beiden verwenden kann?

**Comment by nchiapol** [comment]
Unterdessen ist #80 auf der Integration. Die Mails funktionieren soweit in Ordnung. Zudem wird damit neu auch das Problem aus dem 2. Punkt korrekt gelöst und es werden die nötigen Warnungen angezeigt. 

Aus meiner Sicht muss hier vorerst nichts mehr geändert werden. Es gibt noch ein paar unschöne Details (vgl. unten), die wir aber mit passenden Formulierungen im Mailtext und einer Anleitung für die Kursadministratoren abdecken können. Wir wollen hier also vorerst keine zusätzliche Zeit investieren.


unschöne Details:
  * Effekt von "Verwendet Voranmeldung" und "Wartelieste" könnte gemäss oben konsolidiert werden.
  * Bei Ablauf (a) mit genügen Platz im Kurs erhält die TN im Webinterface den Hinweis, dass sie erst vorangemeldet sei. Sie bekommt aber dann gleich zweimal das "Anmeldung bestätigt" mail. Zudem wird beim Kurs dann auch die korrekte "du bist angemeldet" meldung angezeigt.

Wir testen die verschiedenen Abläufe Ende Monat noch ausgiebig. Falls wir dann noch Zeit übrig haben, können wir immer noch Optimierungen vornehmen.

**Comment by maede97** [comment]
![image](https://user-images.githubusercontent.com/14098502/204355851-5a46d2ca-1c7c-429f-8a06-224443d34a8b.png)
Das Feld "Zustand" ist verwirrend, wenn die Anmeldung noch nicht definitiv ist.
Es müsste heissen:
"Vorangemeldet" und danach "Zugeteilt" (anstelle von "Angemeldet" und "Zugeteilt")

**Comment by nchiapol** [comment]
Sammlung der Wünsche
  - nur  zwei Konfigurationsoptionen für Kurs, mit sinnvollen Texten
  - Voranmeldungs Info-Box + Voranmeldungs-Email nicht nötig in Ablauf (a)
  - Info-Box: "... Voranmeldung für DIE Teilnahme von ..."

**Comment by nchiapol** [comment]
Uns ist noch etwas aufgefallen: Solange eine Anmeldung unter "Anmeldungen" noch auf der rechten Seite (also noch nicht zugeteilt) ist, wird diese Anmeldung auf der Profilseite auch separat aufgeführt: 
![image](https://user-images.githubusercontent.com/1123483/204733982-443b12c9-546f-4962-be77-ed66ff9a462c.png)
Klicke ich auf diesen Link, komme ich auf .../events/.../participations/... (https://cevi.puzzle.ch/groups/6/events/1171/participations/127823) auf allen anderen Wegen erreicht man nur .../events/... (https://cevi.puzzle.ch/groups/6/events/1172).

Das ist grundsätzlich ok, allerdings wird auf dieser Seite der Hinweis "Du bist für diesen Anlass vorangemeldet. Die Anmeldung ist noch nicht definitiv und muss von der Kursadministration bestätigt werden." nicht angezeigt. Damit alles konsistent ist, wäre es super, wenn das dort auch noch angezeigt werden könnte (oder der Link ebenfalls direkt auf .../events/... verweisen würde.)
