### ISSUE TITLE
EVENTS: Mailtext Bestätigungsmail abhängig von Konfiguration Kurs

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_cevi#80]
Die Kommunikation muss noch verbessert werden. Aktuell ist aus dem bestätigungs Mail mit dem PDF nicht ersichtlich, dass die Anmeldung noch nicht final ist. 

### Tech spec
- Umsetzung im Core

### TODO
- [x] In [`Event::ParticipationsController#set_success_notice`](https://github.com/hitobito/hitobito/blob/master/app/controllers/event/participations_controller.rb#L312..L321) einen weiteren Spezialfall einbauen, der eine andere Message ausgibt falls `entry.application == true` ist
- [x] In [banner_participating](https://github.com/hitobito/hitobito/blob/master/app/views/events/_banner_participating.html.haml#L7) eine Unterscheidung mit einer anderen Übersetzung einführen, falls `@user_participation.application == true` ist
- [x] Neues Mail welches statt `Event::ParticipationMailer.confirmation` ausgelöst wird falls `participation.application == true` ist
  - [x] Neuen Mailtext als CustomContent in https://github.com/hitobito/hitobito/blob/master/db/seeds/custom_contents.rb#L329 erfassen
  - [x] Im `Event::ParticipationMailer` eine neue Methode für das neue Mail erstellen (viel Spass bei der Namensfindung, Warteliste und provisorische Anmeldung sind bereits von anderen Konzepten in hitobito besetzt)
  - [x] Im `Event::ParticipationConfirmationJob` das neue Mail auslösen, falls `participation.application == true` ist
- [x] [PDF-Export](https://github.com/hitobito/hitobito/blob/master/app/domain/export/pdf/participation.rb) anpassen gemäss Anforderungen (genauere Beschreibung vom Cevi ist noch offen)
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen und neu verfügbarem CustomContent informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
Aus den für den User sichtbaren Infos ist nicht ersichtlich, dass seine Anmeldung bei einem Kurs erst auf dem "Anmelden"-Tab gelandet ist und er noch manuell dem Kurs zugewiesen werden muss.

  * Bestätigung nach Anmeldung
![image](https://user-images.githubusercontent.com/1123483/161398605-dbbffe8c-e7ac-4bdb-b4b5-af17375c1aa1.png)

  * Kurs-Seite nach Anmeldung
![image](https://user-images.githubusercontent.com/1123483/161398661-494e24b6-2d70-4e76-a1e2-889a2ad2c194.png)

  * Mail-Text "Anmelde-Bestätigung"

  * Inhalt Anmelde-PDF

Die Texte können zum Teil via Einstellungen angepasst werden. Da die Texte aber für alle Anlässe gelten und der Prozess zwischen Kursen und anderen Anlässen unterschiedlich ist, lässt sich das nicht darüber lösen.

Bei Kursen (falls #79 umgesetzt wird nur solche mit Ablauf (b)) soll an all diesen Stellen klar ersichtlich sein, dass die Anmeldung erfasst wurde, aber noch manuell geprüft wird, bevor sie definitiv ist.
Für die Texte in Einstellungen bedeutet dies wohl zwei verschiedene Mail-Vorlagen.

**Comment by mtnstar** [comment]
@nchiapol ich habe den Betreff des neuen Mails mal 'Anfrage Anmeldung' bezeichnet damit gleich klar ist das die Anmeldung in dem beschriebenen Fall noch nicht bestätigt ist.

ich frage mich gerade ob es Sinn macht das bei diesem Mail auch ein PDF als Anhang mitgeschickt wird. Im PDF für die definitive Anmeldung sind ja schon recht detaillierte Informationen sowie auch Felder für Unterschrift usw. vorhanden. 

Ist es aus deiner Sicht ok wenn wir das PDF für die Anfrage weglassen oder willst du uns noch den Inhalt dazu geben?

PDF für die Anmeldung sieht so aus:

![image](https://user-images.githubusercontent.com/655627/199645621-0052d96e-163d-4cd7-ab65-4a6a477c7708.png)

**Comment by nchiapol** [comment]
Vielen Dank für die Rückfrage und den Hinweis auf das PDF. 

* Bezeichnung: eine klare Bezeichnung macht sicher Sinn. "Anfrage Teilnahme" scheint mir aber fast etwas schwach. Alternativen wären "Voranmeldung erhalten", "provisorische Anmeldung". Ich frage mal in unserem Team noch nach ob jemand eine besonders gute Ideen für den Betreff hat.
* PDF: Das ist ein guter Hinweis. Dieses PDF muss mit dem "Anfrage Teilnahme" mail versendet werden. Ein Verwendungszweck des zweistufigen Ablaufs ist, dass wir so die Unterschrift kontrollieren können.

**Comment by carlobeltrame** [comment]
Hinweis: Die Bezeichnungen "Warteliste" und "provisorische Anmeldung" sind bereits von anderen Konzepten in hitobito besetzt.

**Comment by mtnstar** [comment]
@nchiapol super, dann verwenden wir doch den Begriff Voranmeldung. 

soll dann der Inahlt des PDFs gleich sein wie das von der Teilnahmebestätigung? Ausser der Titel heisst anstatt Kursanmeldung -> Voranmeldung ?

kannst du mir noch Bescheid geben falls es im PDF selber andere Inhalte benötigt?

**Comment by nchiapol** [comment]
* Begriff: "Voranmeldung" passt.
* PDF: Der Inhalt des PDFs kann aus meiner Sicht identisch sein und auch der Titel "Kursanmeldung" ist ok. Das zweite Mail nach der Zuweisung zum Kurs braucht dann kein PDF mehr. (Macht aber auch nichts, wenn dort das PDF noch einmal verschickt wird.)  

Der Ablauf ist also:
1. TN meldet sich an
2. TN erhält "Voranmeldung erhalten" E-Mail mit PDF der Anmeldung. Im Mail-Text erläutern wir, dass die Anmeldung erst definitiv wird, wenn wir alle Bedingungen kontrolliert und falls nötig die relevanten Unterschriften erhalten haben.
3. Wir kontrollieren die Bedingungen/TN sendet das unterschrieben Dokument ein.
4. Wir verschieben TN auf dem "Anmeldungen"-Tab nach "Zugeteilte Teilnehmende"
5. TN erhält zweites Mail mit Info, dass Anmeldung bestätigt wurde und nun definitiv gültig ist.

(Eigentlich könnte man sagen, dass nicht das Mail unter (2) sondern jenes unter (5) neu ist.)

**Comment by nchiapol** [comment]
Habe das eben angeschaut, sieht sehr hübsch aus. Danke.

Offene Anliegen schreibe ich in #79, da die verbleibenden Wünsche primär die Effekte der verschiedenen Konfigurationen betrifft.

**Comment by richardjubla** [comment]
Lieber @ThomasEllenberger 

Wie kann ich nachvollziehen, was im Zusammenhang mit diesem Change (Referenz aus Changelog Version 1.28) verändert wurde?

**Comment by richardjubla** [comment]
Bezeichnend für die Situation, es betrifft die Kursverwaltung....


- Dieser Change wird/soll gemäss beschrieb im Core umgesetzt
- Der Change ist mit Version 1.3 im Changelog von 1.28 bei uns (jubla) neu (rückwirkend?) aufgetaucht
- Gemäss Informationen gehen wir davon aus, dass die Anliegen zusammen mit cevi#79 gemacht wurden und in den PR's von diesem Issue umgesetzt wurden.
**- Uns ist nicht klar, was und wie nun auf core/jubla für uns relevant oder zu testen ist**

Version 1.28.30.2
![image](https://github.com/hitobito/hitobito_cevi/assets/95908537/d2bbe958-8cb0-46b2-9b9d-2bc0b9c9ba45)
Version 1.30.20
![image](https://github.com/hitobito/hitobito_cevi/assets/95908537/922524b4-18ad-4b75-97e5-6b3308da2db4)
