### ISSUE TITLE
EVENTS: Hauptleiter haben gleiche Rechte wie Geschäftsstellen

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_cevi#82]
Wir wünschen uns, dass sowohl die Geschäftsstellen wie auch die Hauptleiter die Kurse verwalten können.

Hauptleitung soll auf eigenem Kurs gleiche Rechte wie GS habe (Anmelde-Tab, Bearbeiten)

### Tech Spec
- Umsetzung im Cevi Wavon

### ToDo
- [x] Die Permissions von `Event::Role::Leader` um eine neue Permission `:manage_attendances` erweitern
- [x] Event Ability für den Cevi anpassen, sodass diese Permission einem auch `may(:application_market)` und `may(:index_invitations)` erlaubt
  - [ ] Achtung: Nicht einfach eine neue Zeile hinzufügen, die bisherigen Bedingungen müssen auch miteinbezogen werden. Also müssen vermutlich neue Methoden `in_same_layer_if_active_or_manage_attendances` sowie `in_same_group_or_manage_attendances_and_invitations_supported` erstellt werden

**Comment by nchiapol** [comment]
Denke das ist klar so. Sonst bitte nachfragen.

**Comment by ThomasEllenberger** [comment]
Ich habe dies kurz getestet.
Meines Erachtens hat die Hauptleitung eines Kurses hier bereits die vollen Rechte.
Ich konnte als Hauptleiter die Kursdaten verändern und Teilnehmende verwalten.

@nchiapol kannst du hier genauer spezifizieren, welche Rechte der Hauptleitung aktuell fehlen, oder welche Usecases aktuell nicht abgedeckt sind?

**Comment by nchiapol** [comment]
Stimmt, bearbeiten scheint bereits zu funktionieren. 

Für uns ist aber auch wichtig, dass die Hauptleitung Zugang zum Anmeldungen (und zu den Einladungen) hat. Je nach Kurs kümmert sich eher die Geschäftsstelle oder die Hauptleitung um beide Anliegen. 

### Ansicht Hauptleitung
![image](https://user-images.githubusercontent.com/1123483/197171890-e894d0fe-ff61-4ae5-8a31-c2372e0d292e.png)

### Ansicht Geschäftsstelle
![image](https://user-images.githubusercontent.com/1123483/197172306-c76f1260-81a9-4250-a072-102d9e243211.png)

**Comment by ThomasEllenberger** [comment]
Hebe erneut getestet, und kann das bestätigen. Vermutlich hatte ich dies zuvor mit einer Person mit zuvielen Rechten getestet. 

## Anforderungen
Hauptleitende sollen in Kursen in welchen sie Hauptleitende sind die beiden Tabs "Anmeldungen" und "Einladungen" ebenfalls sehen und bearbeiten können.

**Comment by carlobeltrame** [comment]
@nchiapol ich habe in #99 auch gleich noch das Tab "Provisorische Anmeldungen" für Kursleitende erlaubt, da der generelle Titel dieses Issues "gleiche Rechte" verlangt. Falls das nicht gewünscht ist, bitte melden.

**Comment by nchiapol** [comment]
@carlobeltrame Vielen Dank für den Hinweis. Das sollte passen.

**Comment by nchiapol** [comment]
@ThomasEllenberger

Habe das nun eben getestet:
  * Tab Info: Der Hauptleiter kann alle Kurseinstellungen bearbeiten, Anhänge hinzufügen sowie den Direktlink kopieren. Der Hauptleiter kann nicht: Sich selbst vom Kurs abmelden, den Kurs löschen oder duplizieren. Ausserdem fehlt bei ihm der Knopf "Kalender Export", keine Ahnung weshalb.
  * Tab Teilnehmende: Der Hauptleiter hat die gleichen Rechte wie die GS und kann Team-Mitglieder erfassen. Er kann keine Rechnungen erzeugen. (Dafür ist wahrscheinlich das entsprechende Rechte auf der Eben nötig.)
  * Das Tab Anmeldungen wird beim Hauptleiter angezeigt, der Knopf "Teilnehmer/in hinzufügen" fehlt jedoch. Das kann weiterhin nur die Geschäftsstelle (und natürlich der Teilnehmer selbst, wenn er sich über die DB anmeldet). Der Hauptleiter kann aber Personen zwischen den Stati "Warteliste/Vorangemeldet" und "Zugeteilt" verschieben.
  * Der Hauptleiter kann Qualifikationen erfassen.
  * Das Tab "provisorische Anmeldungen" wird beim Hauptleiter auch dann angezeigt, wenn provisorische Anmeldungen für den Kurs gar nicht aktiviert sind. (In dem Fall ist das Tab einfach leer.)
  * Tab Einladungen: Wird angezeigt, der Versuch jemanden einzuladen schlägt aber mit der Meldung "Sie sind nicht berechtigt, diese Seite anzuzeigen" fehl (https://github.com/hitobito/hitobito/issues/1495)

Alles in allem scheint das für mich so ok. 
  * "Kalender Export" und "provisorische Anmeldungen" sind kosmetische Probleme. Wenn sich die rasch fixen lassen, hilft das sicher der Qualität der DB.
  * "Teilnehmer/in hinzufügen" ist für unsere Region sicher ebenfalls ok. Die TN-Anmeldungen sollten nicht über den Hauptleiter laufen. Ich erwarte nicht, dass das für andere Nutzer bei uns ein Problem ist, sonst melden wir uns wie versprochen noch separat.

**Comment by nchiapol** [comment]
@ThomasEllenberger @carlobeltrame 

Für andere Regionen ist das Hinzufügen von Teilnehmer/innen relevant. Könnt ihr das also bitte doch noch anpassen? Oder ist das mit grossem Zusatzaufwand/unschönen Nebenwirkungen verbunden?

**Comment by nchiapol** [comment]
@ThomasEllenberger @carlobeltrame 

Weitere Tests (durch @tschuepbach) haben noch zwei fehlende Knüpfe gefunden: Auf der Participation (z.b. https://cevi.puzzle.ch/groups/5/events/1178/participations/127844) fehlen für den Hauptleiter die Knöpfe für "Anmeldung löschen" und "Ablehnen". (letzteren Knopf sieht, wenn man bei einer noch nicht zugeteilten Person im "Anmeldungen"-Tab auf den Namen klickt und so die participation öffnet).

Könnt ihr bitte den "Ablehnen"-Knopf ebenfalls noch einbauen? Bei verschiedenen unserer Prozesse ist es relevant, dass die Hauptleiter diese Möglichkeit haben. Dass Hauptleiter Anmeldungen nicht ganz löschen können ist aus meiner Sicht ein Feature - falls die Knöpfe aber nur gemeinsam aktiviert werden können, ist es wichtiger, dass der "Ablehnen"-Knopf angezeigt wird.

**Comment by ThomasEllenberger** [comment]
Habe dies auch kurz getestet und kann die oben genannten Punkte bis auf den letzten bestätigen.

@nchiapol auf einem Teilnehmer hat es für die Geschäftsstelle die Knöpfe "Anmeldung löschen" sowie "Abmelden". Wenn ich mich mit den Hauptleiter imitiere sehe ich den button "Abmelden" jedoch nicht "Anmeldung löschen":
![image](https://user-images.githubusercontent.com/100761305/218726973-54c202fd-8ab8-4025-9bfe-665392907d78.png)

**Comment by ThomasEllenberger** [comment]
Noch zu tun:

- [ ] Für den Hauptleiter wird das Tab "Einladungen" zwar bereits angezeigt. Versucht man jedoch jemanden einzuladen erhält man die Fehlermeldung "Sie sind nicht berechtigt....". Dies sollte für die Hauptleitung ebenfalls möglich sein. 
- [ ] Beim Hauptleiter fehlt der Knopf "Kalender Export". Sollte auch für Hauptleitung angezeigt werden.
- [ ] "Provisorische Anmeldungen" wird beim Hauptleiter auch dann angezeigt, wenn provisorische Anmeldungen für den Kurs gar nicht aktiviert sind. Dies sollte korrekt nur dann angezeigt werden wenn dies auf dem Kurs auch aktiviert ist.
- [ ] Auf der Participation fehlen für den Hauptleiter die Knöpfe "Anmeldung löschen" und "Ablehnen" - Bitte "Ablehnen" Knopf ergänzen. "Anmeldung löschen" nur wenn dies mit "Ablehnen" zusammenhängt, sonnst nicht. --> Dies ist gemäss mit bereits korrekt! Bitte noch bestätigen.

**Comment by nchiapol** [comment]
@ThomasEllenberger zu deiner Liste:
* Einladungen: Wie oben verlinkt ist das ein allgemeiner Bug - bei uns funktionieren Einladungen auch als Geschäftsstelle nicht. (sondern wohl nur als Admins) Das muss nicht in diesem Issue gefixt werden - wenn es zeitlich passt darf das aber natürlich ;-)
* Kalender Export: ist für uns nicht wichtig aber sicher nice to have
* Provisorische Anmeldungen: ist für uns nicht wichtig aber sicher nice to have
* Ablehnen: Nein, dein Screenshot zeigt den "Abmelden" Knopf, das ist nicht das gleich: 
![image](https://user-images.githubusercontent.com/1123483/218878317-d4e25a8e-ff8f-41b3-86a7-55f0d395d8c6.png)
(Wie in https://github.com/hitobito/hitobito_cevi/issues/82#issuecomment-1425434397 beschrieben betrifft das nur Anmeldungen die noch nicht zugewiesen sind.)
* **fehlt noch**: "Teilnehmer/in hinzufügen" auf dem Anmeldungen Tab. Entgegen meiner ersten Einschätzung ist das für einige Regionen bei uns relevant (https://github.com/hitobito/hitobito_cevi/issues/82#issuecomment-1425755538)
