### ISSUE TITLE
KURSE: J+S Nummer, AHV-Nummer und Nationalität bei Anmeldungen anzeigen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_cevi#98]
# Anforderungen

Als Person welche die Zulassungsbedingungen für Kurse prüfen muss, möchte ich die J+S Nummer und AHV-Nummer von Teilnehmenden direkt auf dem "Anmeldungen " Tab von Kursen sehen. Damit soll der Prozess vereinfacht werden, indem man diese Daten nicht separat in Hitobito oder der NDS suchen muss.

- Basiert auf folgendem Kommentar: https://github.com/cevi/hitobito_cevi/issues/101#issuecomment-1136257437
- Bei -> Kursen -> Tab "Anmeldungen" die `J+S Nummer` und die `AHV Nummer`  und `Nationalität` anzeigen. (Gemäss Kommentar https://github.com/hitobito/hitobito_cevi/issues/98#issuecomment-1386552113)
- Jeder der die Berechtigung hat das "Anmeldungen" Tab zu sehen, darf auch die neuen Felder sehen.

# Mockup

![image.png](https://user-images.githubusercontent.com/40494600/170099638-07c0a4a0-666a-4753-896e-76742507cd8f.PNG)

# Tech-Spec

- Zulassungsbedingungen sollen leichter prüfbar sein
- Umsetzung im Youth-Wagon

# ToDo

- [ ] View `app/views/event/participations/_application_details.html.haml` anpassen
	- [ ] `ahv_number`
	- [ ] `j_s_number`
	- [ ] `nationality_j_s`
- [ ] ggf. Specs anpassen
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
@ThomasEllenberger Ich nehme an, die Nationalität macht beim Aufwand keinen relevanten Unterschied. Entsprechend gerne. (@tschuepbach melde dich, falls du anderer Meinung bist)

**Comment by nchiapol** [comment]
@ThomasEllenberger getestet, funktioniert
